version: "3"

volumes:
  hessab-data:
    name: hessab-data
  nokteh-data:
    name: nokteh-data

networks:
  hessab-network:
    name: hessab-network
  nokteh-network:
    name: nokteh-network

services:
  hessab:
    networks:
      - hessab-network
    image: "ghcr.io/aminwhat/vazir_hessab:master"
    container_name: hessab
    restart: always
    ports:
      - 3779:3779
    expose:
      - 3779:3779
    depends_on:
      - hessab_db

  hessab_db:
    networks:
      - hessab-network
    image: mongo:6.0
    volumes:
      - hessab-data:/
    container_name: hessab_db
    restart: always
    hostname: hessab_db
    expose:
      - 27117:27017
    ports:
      - 27117:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aminwhat
      - MONGO_INITDB_ROOT_PASSWORD=amin5623

  nokteh:
    networks:
      - nokteh-network
    image: "ghcr.io/aminwhat/vazir_nokteh:master"
    container_name: nokteh
    restart: always
    ports:
      - 3779:3779
    expose:
      - 3779:3779
    depends_on:
      - nokteh_db

  nokteh_db:
    networks:
      - nokteh-network
    image: mongo:6.0
    volumes:
      - nokteh-data:/
    container_name: nokteh_db
    restart: always
    hostname: nokteh_db
    expose:
      - 27117:27017
    ports:
      - 27117:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aminwhat
      - MONGO_INITDB_ROOT_PASSWORD=amin5623
