version: "3"

volumes:
  data:
    name: data

networks:
  center-network:
    name: center-network

services:
  hessab:
    networks:
      - center-network
    image: "ghcr.io/aminwhat/vazir_hessab:master"
    container_name: hessab
    restart: always
    ports:
      - 3779:3779
    expose:
      - 3779:3779
    depends_on:
      - hessab_db

  hessab_db:
    networks:
      - center-network
    image: mongo:6.0
    volumes:
      - data:/data/db
    container_name: hessab_db
    restart: always
    hostname: hessab_db
    expose:
      - 27117:27017
    ports:
      - 27117:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aminwhat
      - MONGO_INITDB_ROOT_PASSWORD=amin5623
