apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  ports:
    - name: "27117"
      port: 27117
      targetPort: 27017
    - name: "0"
      port: 0
      targetPort: 0
  selector:
    io.kompose.service: mongo
